name: Deploy Countdown Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "$(echo '${{ secrets.DEPLOY_HOST }}' | tr -d '\r\n')" >> ~/.ssh/known_hosts


      - name: List files for deployment (debug)
        run: ls -lah

      - name: Deploy via rsync
        run: |
          rsync -avz --delete \
            --exclude=".git/" \
            --exclude=".github/" \
            ./ root@${{ secrets.DEPLOY_HOST }}:/var/www/chuffchart.org/html/countdown/
# Deploy updated at Fri 11 Jul 2025 10:21:17 BST
# Force rebuild Fri 11 Jul 2025 10:37:06 BST
