name: Deploy Countdown Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 134.209.25.249 >> ~/.ssh/known_hosts


      - name: List files for deployment (debug)
        run: ls -lah

      - name: Deploy via rsync
        run: |
          rsync -avz --delete \
            --exclude=".git/" \
            --exclude=".github/" \
            ./ root@134.209.25.249:/var/www/chuffchart.org/html/countdown/
