name: Deploy Countdown Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          HOST=$(echo "${{ secrets.DEPLOY_HOST }}" | tr -d '\r\n')
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - name: Deploy site via rsync
        run: |
          HOST=$(echo "${{ secrets.DEPLOY_HOST }}" | tr -d '\r\n')
          rsync -avz --delete \
            --exclude=".git/" \
            --exclude=".github/" \
            ./ deploy@"$HOST":/var/www/chuffchart.org/html/countdown/

      - name: Verify deployment
        run: |
          sleep 5
          curl -s https://chuffchart.org/countdown/ | grep -i "countdown" || (echo "Deployment verification failed" && exit 1)

